fix/feat-forgot-password-added
VanshKing30/FoodiesWeb pull request #273
Opened 2024-06-08 12:50 UTC by Adityajparmar37

Forgot Password Feature added

Fixes #207 

## PLEASE NOTED
IN ENV VARIAVLE FILE (.env) added following things without it feature will not work neither can be check

1) EMAIL="Added your email address";
2) MAILPASS="Add password for allowing mailing outside gmail mail service";

## To GENERATE MAILPASS
https://myaccount.google.com/apppasswords?rapt=AEjHL4PAhcbtFEpLwfNtVix3bfiGe71GdrW_Naiuvp_NVnMZyTd0UR07M2mVnEyWzkw9kB99YVhhfEVtjxTi3QWSZ39biK-zGwnghm0u778vwmlh6TFbmh4

**Go to this link and create *New APP PASSWORD*** 

## NOTE
***In https://myaccount.google.com/security, do you see 2-step verification set to *ON****

## Type of change
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Yes for both student and canteen 

# Screenshorts and Vedios:
https://github.com/VanshKing30/FoodiesWeb/assets/105008414/5ffb632e-741f-4b56-b3b3-17966975c5ef

# Checklist:
give a X on it which is applicable

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-06-08 12:51 UTC, Adityajparmar37 commented
Please review the code

2024-06-08 13:51 UTC, aayushchugh requested changes
Can you please update the required `.env` variables in `README` too?

2024-06-08 17:30 UTC, Adityajparmar37 commented
> Can you please update the required `.env` variables in `README` too?

I can but the thing is i cannot give my EMAIL or MAILPASS key

2024-06-08 17:42 UTC, Adityajparmar37 commented
I have added .env in README file please refer it

2024-06-09 03:28 UTC, hustlerZzZ commented
> I have added .env in README file please refer it

Kindly resolve the conflicts... @Adityajparmar37

2024-06-09 03:28 UTC, hustlerZzZ requested changes
Resolve the conflicts

2024-06-09 04:59 UTC, aayushchugh requested changes
Reset looks good, amazing job @Adityajparmar37 💪🏼

2024-06-09 04:59 UTC, aayushchugh commented on README.md
> +   MAILPASS="mail pass key ( app password)"
Change this too

```
EMAIL="The email from which forgot the password email will be sent"
MAILPASS="password for the email ( app password )"
```

and provide a link to generate an app password too

2024-06-09 05:14 UTC, aayushchugh approved these changes
LGTM 🚀

2024-06-09 05:34 UTC, Adityajparmar37 commented
Branch conflicts has been resolve plz review the code again

2024-06-09 07:26 UTC, hustlerZzZ approved these changes
Great Work Buddy

2024-06-09 07:27 UTC, merged

2024-06-09 07:56 UTC, Adityajparmar37 commented
Hey , can you please check why production or deployment has been failed . 

![image](https://github.com/VanshKing30/FoodiesWeb/assets/105008414/852d8237-2efa-46b8-9211-62c09f8dc12f)


Please check it