Solved issue 182
VanshKing30/FoodiesWeb pull request #284
Opened 2024-06-09 11:50 UTC by Saksham2k3s

This change addresses and fixes issue #182, which involves displaying the error message from the backend in a toast notification upon login and signup failure.

Fixes #182 

## Type of change

Please give a X on it which is applicable

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshorts and Vedios:

give screenshorts and vedio of the changes you made

# Checklist:
give a X on it which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-06-10 05:04 UTC, Adityajparmar37 requested changes

2024-06-10 05:04 UTC, Adityajparmar37 commented on src/pages/Login.jsx
> -                  required
Why did you remove required ?? it is important to have password

2024-06-10 05:04 UTC, Adityajparmar37 commented on src/pages/Signup.jsx
> -                    required
Here also why did you remove required

2024-06-10 11:12 UTC, Saksham2k3s commented
Sorry, it was a mistake. I was only testing some cases by removing this.

2024-06-10 11:58 UTC, Saksham2k3s commented
I've added required in the input field

2024-06-10 13:43 UTC, Adityajparmar37 approved these changes

2024-06-11 02:26 UTC, hustlerZzZ approved these changes
Ok great work

2024-06-11 02:26 UTC, merged